services:
  - type: web
    name: peerpath-app
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: peerpath-server
          property: url
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: peerpath-server
    runtime: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    plan: free
    rootDir: server
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BREVO_USER
        sync: false
      - key: BREVO_PASS
        sync: false
